---
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Data Science Projects In-progress

- [Death Penalty](https://github.com/ryanbieber/Death-Penalty) A very interesting dataset given by [data-is-plural](https://tinyletter.com/data-is-plural) which has a ton of different datasets given every Wednesday. I haven't decided what I want to do with this yet. 

- [Weightlifitng Medal Prediction](https://github.com/ryanbieber/Weightlifting) During the 2019 IWF Championship I wanted to see if it was possible to predict who might win a medal based on certain characteristics such as weight difference from weight class, country, sex, etc. It turns out that using only a few variables we are able to get a relatively accurate prediction(82%) based only on few variables.

## Data Science Projects Completed

- [World of Warcraft, Black Market Gold](https://github.com/ryanbieber/Wow-Gold) The whole point of this project was to look at how patches impacted gold prices in world of warcraft. It evolved into trying to predict when to *buy gold* in the mmo to try and play the market just like in the stock market. It turns out that gold prices are very unpredicitable and follow a more or less stochastic trend.

- [Twitter NLP](https://github.com/ryanbieber/NLP) This was brought about by being intrested in seeing if we could predict the stock market based on twitter sentiment. using [sentimentr](https://cran.r-project.org/web/packages/sentimentr/sentimentr.pdf) we are able to determine the sentiment of string of texts. Using this, we are able to get a time-series of someones sentiment. Long story short, it didn't work out as I wanted it to but, it is pretty cool to see someones sentiment over time using their twitter data.

- [Deploying plumber in the IBM Cloud](https://github.com/ryanbieber/deploying-plumber-ibm-cloud) This was more of a learning experience with understanding how a full-stack web application works with R. Also, connecting to a DB2 from a container is somewhat annoying if you have to use that dbms.