---
---

## Training 

I train usually in a 4 day cycle (Monday, Wednesday, Friday, and Saturday) with many other workouts in between when I get bored (mainly abs). Personally, my favorite lifts are dips and deadlifts as you can see below here are some current lifts with a 505x5 on the deadlift and 225+bw dip which comes out over 400lbs. I mainly post some of my training on Instagram as it is just easier to capture and store the videos like that. Here are a couple of some recent lifts I have done.


### Deadlift 505x5

<video width="720" height="480" controls>
  <source src="videos/deadlift505x5.mp4" type="video/mp4">
</video>

### Dip bw(190ish)+225

<video width="720" height="480" controls>
  <source src="videos/dip225.mp4" type="video/mp4">
</video>

### Sample week 5 weeks out from a show

#### D1 

(Main) 

Axel Strict Press (Clean from Ground)	

90.00%	3x1

80.00%	3x5

(Main Assistance)

Close grip bench 4x10 RPE8

Vertical Pulling 4x8-10	RPE 8

(Assistance) 

(Superset)	

Dips (5 sec eccentric)	5x10	RPE 9

21s		5 sets	RPE 9

Shoulder Raises		5x15	RPE 9

#### D3

(Main)

Deadlift

70.00%	4x4

80.00%	1x2

90.00%	1x2

70.00%	1x12

(Main Assistance)

Single Leg Squats	3x10	RPE 8

Horozontail Pulling	4x15	RPE 9

(Assistance)

(Superset)	

Leg extensions	4x20 (Light)

GHR	4x20	bw

Abs			

#### D5

(Main)

Log press	

90.00%	3x1

80.00%	3x5

(Main Assistance)

Box Front Squats 5x5	RPE 9 (static hold last rep)

(Assistance)

Weighted pullups (neutral grip)	5 sets	RPE 9	*pick a weight that you get 12 on the first set

Tricep drop set	Work up to a heavy set of 10 in 4 sets then work back down in 4 sets to the weight you started at	

Rear delt fly machine	5x15	Rpe 9	

#### D6

(Event Day)

Farmers	80.00%	5 sets
		
Grip work(if you can after farmers)		
		
Events 	

-stones

-carry medley

Abs		

